# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import option_pricing.grpc_option.option_pb2 as option__pb2


class OptionPricingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputePrice = channel.unary_unary(
                '/OptionPricing/ComputePrice',
                request_serializer=option__pb2.ComputeRequest.SerializeToString,
                response_deserializer=option__pb2.UxtSlice.FromString,
                )


class OptionPricingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputePrice(self, request, context):
        """Method to compute option price
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptionPricingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputePrice,
                    request_deserializer=option__pb2.ComputeRequest.FromString,
                    response_serializer=option__pb2.UxtSlice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OptionPricing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OptionPricing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OptionPricing/ComputePrice',
            option__pb2.ComputeRequest.SerializeToString,
            option__pb2.UxtSlice.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
