# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: option.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coption.proto\"\xe5\x01\n\x0e\x43omputeRequest\x12\x10\n\x08maxPrice\x18\x01 \x01(\x01\x12\x12\n\nvolatility\x18\x02 \x01(\x01\x12\t\n\x01r\x18\x03 \x01(\x01\x12\x0c\n\x04tMax\x18\x04 \x01(\x01\x12\x13\n\x0bstrikePrice\x18\x05 \x01(\x01\x12\x17\n\x0f\x63\x61lculationType\x18\x06 \x01(\t\x12\x0c\n\x04\x62\x65ta\x18\x07 \x01(\x01\x12\x12\n\nstartPrice\x18\x08 \x01(\x01\x12\x18\n\x10maturityTimeDays\x18\t \x01(\x05\x12\x15\n\rexpectedPrice\x18\n \x01(\x01\x12\x13\n\x0boptionStyle\x18\x0b \x01(\t\"\xa6\x01\n\x08UxtSlice\x12\x0f\n\x01U\x18\x01 \x03(\x0b\x32\x04.Uxt\x12\x1d\n\x15\x43\x61lculatedOptionprice\x18\x02 \x01(\x01\x12 \n\x18\x43\x61lculatedExpirationDays\x18\x03 \x01(\x05\x12\x1c\n\x14\x43\x61lculatedAssetPrice\x18\x04 \x01(\x01\x12\x16\n\x0e\x43\x61lculatedBeta\x18\x05 \x01(\x01\x12\x12\n\nPriceIndex\x18\x06 \x01(\x05\"\x11\n\x03Uxt\x12\n\n\x02Ut\x18\x01 \x03(\x01\x32=\n\rOptionPricing\x12,\n\x0c\x43omputePrice\x12\x0f.ComputeRequest\x1a\t.UxtSlice\"\x00\x42\nZ\x08.;optionb\x06proto3')



_COMPUTEREQUEST = DESCRIPTOR.message_types_by_name['ComputeRequest']
_UXTSLICE = DESCRIPTOR.message_types_by_name['UxtSlice']
_UXT = DESCRIPTOR.message_types_by_name['Uxt']
ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREQUEST,
  '__module__' : 'option_pb2'
  # @@protoc_insertion_point(class_scope:ComputeRequest)
  })
_sym_db.RegisterMessage(ComputeRequest)

UxtSlice = _reflection.GeneratedProtocolMessageType('UxtSlice', (_message.Message,), {
  'DESCRIPTOR' : _UXTSLICE,
  '__module__' : 'option_pb2'
  # @@protoc_insertion_point(class_scope:UxtSlice)
  })
_sym_db.RegisterMessage(UxtSlice)

Uxt = _reflection.GeneratedProtocolMessageType('Uxt', (_message.Message,), {
  'DESCRIPTOR' : _UXT,
  '__module__' : 'option_pb2'
  # @@protoc_insertion_point(class_scope:Uxt)
  })
_sym_db.RegisterMessage(Uxt)

_OPTIONPRICING = DESCRIPTOR.services_by_name['OptionPricing']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010.;option'
  _COMPUTEREQUEST._serialized_start=17
  _COMPUTEREQUEST._serialized_end=246
  _UXTSLICE._serialized_start=249
  _UXTSLICE._serialized_end=415
  _UXT._serialized_start=417
  _UXT._serialized_end=434
  _OPTIONPRICING._serialized_start=436
  _OPTIONPRICING._serialized_end=497
# @@protoc_insertion_point(module_scope)
