// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: option.proto

package option

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OptionPricingClient is the client API for OptionPricing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptionPricingClient interface {
	// Method to compute option price
	ComputePrice(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*UxtSlice, error)
}

type optionPricingClient struct {
	cc grpc.ClientConnInterface
}

func NewOptionPricingClient(cc grpc.ClientConnInterface) OptionPricingClient {
	return &optionPricingClient{cc}
}

func (c *optionPricingClient) ComputePrice(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*UxtSlice, error) {
	out := new(UxtSlice)
	err := c.cc.Invoke(ctx, "/OptionPricing/ComputePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptionPricingServer is the server API for OptionPricing service.
// All implementations must embed UnimplementedOptionPricingServer
// for forward compatibility
type OptionPricingServer interface {
	// Method to compute option price
	ComputePrice(context.Context, *ComputeRequest) (*UxtSlice, error)
	mustEmbedUnimplementedOptionPricingServer()
}

// UnimplementedOptionPricingServer must be embedded to have forward compatible implementations.
type UnimplementedOptionPricingServer struct {
}

func (UnimplementedOptionPricingServer) ComputePrice(context.Context, *ComputeRequest) (*UxtSlice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputePrice not implemented")
}
func (UnimplementedOptionPricingServer) mustEmbedUnimplementedOptionPricingServer() {}

// UnsafeOptionPricingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptionPricingServer will
// result in compilation errors.
type UnsafeOptionPricingServer interface {
	mustEmbedUnimplementedOptionPricingServer()
}

func RegisterOptionPricingServer(s grpc.ServiceRegistrar, srv OptionPricingServer) {
	s.RegisterService(&OptionPricing_ServiceDesc, srv)
}

func _OptionPricing_ComputePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptionPricingServer).ComputePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OptionPricing/ComputePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptionPricingServer).ComputePrice(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptionPricing_ServiceDesc is the grpc.ServiceDesc for OptionPricing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptionPricing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OptionPricing",
	HandlerType: (*OptionPricingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputePrice",
			Handler:    _OptionPricing_ComputePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "option.proto",
}
